In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.487587  0.091358 -0.296242 -0.347016
2013-01-02  0.503757  1.290980  1.358702 -0.458898
2013-01-03  0.497645  0.925573 -0.784467  2.315718
2013-01-04 -0.160748  1.416413 -0.753258 -1.140881
2013-01-05  0.533197  0.285367  0.205187 -0.617927
2013-01-06 -0.212733  0.456411  0.315231 -1.380071

In [5]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df

                   A         B         C         D
2013-01-01 -0.487587  0.091358 -0.296242 -0.347016
2013-01-02  0.503757  1.290980  1.358702 -0.458898
2013-01-03  0.497645  0.925573 -0.784467  2.315718
2013-01-04 -0.160748  1.416413 -0.753258 -1.140881
2013-01-05  0.533197  0.285367  0.205187 -0.617927
2013-01-06 -0.212733  0.456411  0.315231 -1.380071

In [8]:
df.to_numpy()

array([[-0.4875872 ,  0.09135846, -0.29624194, -0.347016  ],
       [ 0.50375679,  1.29098009,  1.35870159, -0.45889823],
       [ 0.4976455 ,  0.92557322, -0.78446729,  2.31571802],
       [-0.1607478 ,  1.41641296, -0.75325786, -1.14088124],
       [ 0.53319681,  0.28536731,  0.20518715, -0.61792721],
       [-0.21273344,  0.45641148,  0.31523139, -1.38007072]])

In [9]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01 -0.347016 -0.296242  0.091358 -0.487587
2013-01-02 -0.458898  1.358702  1.290980  0.503757
2013-01-03  2.315718 -0.784467  0.925573  0.497645
2013-01-04 -1.140881 -0.753258  1.416413 -0.160748
2013-01-05 -0.617927  0.205187  0.285367  0.533197
2013-01-06 -1.380071  0.315231  0.456411 -0.212733

In [ ]:
df.sort_values(by=["B","A"])
# 2 based column ni ho ry h / ye jb priority wise h jasy first h 
df.sort_values(by="B")

                   A         B         C         D
2013-01-01 -0.487587  0.091358 -0.296242 -0.347016
2013-01-05  0.533197  0.285367  0.205187 -0.617927
2013-01-06 -0.212733  0.456411  0.315231 -1.380071
2013-01-03  0.497645  0.925573 -0.784467  2.315718
2013-01-02  0.503757  1.290980  1.358702 -0.458898
2013-01-04 -0.160748  1.416413 -0.753258 -1.140881

In [ ]:
# 3/3
df[0:3]
# 2 sy start hoga or 3 index tk print hoga
df[2:3]

                   A         B         C         D
2013-01-01 -0.487587  0.091358 -0.296242 -0.347016
2013-01-02  0.503757  1.290980  1.358702 -0.458898
2013-01-03  0.497645  0.925573 -0.784467  2.315718

In [ ]:
# iloc function ya rows or column 2no btana / index ko loc krny k liye
df.iloc[0:3,1:3]
# df.iloc[:, 1:3]

                   B         C
2013-01-01  0.091358 -0.296242
2013-01-02  1.290980  1.358702
2013-01-03  0.925573 -0.784467

In [17]:
# lock krny k liye via string
df.loc[:, ["A","B"]]

                   A         B
2013-01-01 -0.487587  0.091358
2013-01-02  0.503757  1.290980
2013-01-03  0.497645  0.925573
2013-01-04 -0.160748  1.416413
2013-01-05  0.533197  0.285367
2013-01-06 -0.212733  0.456411

In [18]:
# position k liye
df.iloc[3]

A   -0.160748
B    1.416413
C   -0.753258
D   -1.140881
Name: 2013-01-04 00:00:00, dtype: float64