 How to import dataset in python using pandas library\
 Written by : Qurratulain\
 Date: 08/10/2026\
 Email: dev.quratulain@gmail.com

step -1
import pandas library
step -2
reading/importing dataset

In [5]:
import pandas as pd
df=pd.read_excel("pandas_01_day6.xlsx")
print(df)

    height  weight favourite_dish
0      5.8     101  Chicken Pulao
1      6.2      92        Biryani
2      5.9      62  Karahi Ghosht
3      5.9      95  Chicken Pulao
4      5.9      55  Chicken Pulao
..     ...     ...            ...
82     5.4      55          Pasta
83     5.9      75  Karahi Ghosht
84     5.4      61        Biryani
85     6.2      68  Chicken Pulao
86     5.1      96        Biryani

[87 rows x 3 columns]

In [ ]:
# head k liye just first five show krta h 
df.head()
# agr apni mrzi sy rows jannni ho df.head(10)

   height  weight favourite_dish
0     5.8     101  Chicken Pulao
1     6.2      92        Biryani
2     5.9      62  Karahi Ghosht
3     5.9      95  Chicken Pulao
4     5.9      55  Chicken Pulao

In [ ]:
# tail k liye means sb sy akhri/end py jo data h 
df.tail()
# agr apni mrzi sy rows jannni ho df.tail(17)

    height  weight favourite_dish
82     5.4      55          Pasta
83     5.9      75  Karahi Ghosht
84     5.4      61        Biryani
85     6.2      68  Chicken Pulao
86     5.1      96        Biryani

In [12]:
# shape means that datafram/data ki rows or column ..rows always pahly aye gi 
df.shape

(87, 3)

In [13]:
# info k liye
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   height          87 non-null     float64
 1   weight          87 non-null     int64
 2   favourite_dish  87 non-null     str
dtypes: float64(1), int64(1), str(1)
memory usage: 2.2 KB

In [14]:
# indeces check krny k liye
df.index

RangeIndex(start=0, stop=87, step=1)

In [15]:
# column check krny k 
df.columns

Index(['height', 'weight', 'favourite_dish'], dtype='str')

In [16]:
# numeric columns (numbers wale columns) / dataset ki summary statistics
df.describe()

           height      weight
count   87.000000   87.000000
mean     9.997241   70.459770
std     25.733519   16.753899
min      5.000000   25.000000
25%      5.300000   60.000000
50%      5.600000   70.000000
75%      5.850000   80.000000
max    178.000000  125.000000

In [17]:
# transpose / jo hum math me transpose krty h 
df.T

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
height,5.8,6.2,5.9,5.9,5.9,5.3,5.6,5.9,5.1,5.4,...,5.5,5.11,5.3,5.4,5.5,5.4,5.9,5.4,6.2,5.1
weight,101,92,62,95,55,59,50,76,78,68,...,85,72,62,55,52,55,75,61,68,96
favourite_dish,Chicken Pulao,Biryani,Karahi Ghosht,Chicken Pulao,Chicken Pulao,Biryani,Pasta,Biryani,Biryani,Biryani,...,Biryani,Karahi Ghosht,Biryani,Pasta,Karahi Ghosht,Pasta,Karahi Ghosht,Biryani,Chicken Pulao,Biryani

In [ ]:
# sort data  df.sort_index()
df.sort_index(ascending=False)

    height  weight favourite_dish
86     5.1      96        Biryani
85     6.2      68  Chicken Pulao
84     5.4      61        Biryani
83     5.9      75  Karahi Ghosht
82     5.4      55          Pasta
..     ...     ...            ...
4      5.9      55  Chicken Pulao
3      5.9      95  Chicken Pulao
2      5.9      62  Karahi Ghosht
1      6.2      92        Biryani
0      5.8     101  Chicken Pulao

[87 rows x 3 columns]